### ISSUE TITLE
Can't get latest preview to run on MacOs - Property CliPath: The path to the DCP executable used for Aspire orchestration is required.

### ISSUE THREAD

**Issue by gregpakes** [dotnet/aspire-samples#271]
I am using Rider on MacOS and am using the project templates in the plugin.  The templates use Preview 2.  When I upgrade them to preview 7, it fails to run.

```
dotnet --version
8.0.204
```

```
dotnet workload list

Installed Workload Id      Manifest Version                      Installation Source
------------------------------------------------------------------------------------
aspire                     8.0.0-preview.7.24251.11/8.0.100      SDK 8.0.200        

Use `dotnet workload search` to find additional workloads to install.
```

```
dotnet run

Building...
/usr/local/share/dotnet/packs/Aspire.Hosting.Sdk/8.0.0-preview.7.24251.11/Sdk/Sdk.targets(39,5): warning ASPIRE002: AspireApp1.AppHost is an Aspire AppHost project but necessary dependencies aren't present. Are you missing an Aspire.Hosting.AppHost PackageReference? [/Users/gregpakes/Development/AspireApp1/AspireApp1.AppHost/AspireApp1.AppHost.csproj]
Unhandled exception. System.AggregateException: One or more errors occurred. (Property CliPath: The path to the DCP executable used for Aspire orchestration is required.; Property DashboardPath: The path to the Aspire Dashboard binaries is missing.)
 ---> Microsoft.Extensions.Options.OptionsValidationException: Property CliPath: The path to the DCP executable used for Aspire orchestration is required.; Property DashboardPath: The path to the Aspire Dashboard binaries is missing.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Aspire.Hosting.Dashboard.ConfigureDefaultDashboardOptions.Configure(DashboardOptions options) in /_/src/Aspire.Hosting/Dashboard/DashboardOptions.cs:line 24
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Aspire.Hosting.Dashboard.DashboardLifecycleHook.AddDashboardResource(DistributedApplicationModel model) in /_/src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs:line 77
   at Aspire.Hosting.Dashboard.DashboardLifecycleHook.BeforeStartAsync(DistributedApplicationModel model, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs:line 46
   at Aspire.Hosting.DistributedApplication.ExecuteBeforeStartHooksAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 353
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 309
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 338
   at Program.<Main>$(String[] args) in /Users/gregpakes/Development/AspireApp1/AspireApp1.AppHost/Program.cs:line 5

```

I have tried searching the issues, but can't find anything.

**Comment by gregpakes** [comment]
I resolved this my adding the PackageReference to "Aspire.Hosting.AppHost" to the AppHost project.  I don't know why this isn't in the project templates for Rider, but hopefully this helps someone.
