### ISSUE TITLE
[eShopLite] Exception when navigating to cart

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire-samples#36]
I'm not sure how functional the sample is supposed to be but...

1. Run the eShopLite apphost
2. Navigate to frontend
3. add some things to cart 
4. Click cart
OBSERVE: Cart goes from a count to 0
5. Click cart again
OBSERVE: exception
```
Grpc.Core.RpcException: Status(StatusCode="NotFound", Detail="Basket with buyer id user does not exist")
   at eShopLite.Frontend.Services.BasketServiceClient.CheckoutBasketAsync(String buyerId) in D:\GitHub\aspire-samples\samples\eShopLite\eShopLite.Frontend\Services\BasketServiceClient.cs:line 60
   at eShopLite.Frontend.Components.Cart.HandleCheckout() in D:\GitHub\aspire-samples\samples\eShopLite\eShopLite.Frontend\Components\Cart.razor:line 42
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<WaitForQuiescence>g__ProcessAsynchronousWork|54_0()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.WaitForQuiescence()
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.SendStreamingUpdatesAsync(HttpContext httpContext, Task untilTaskCompleted, TextWriter writer)
```

**Comment by baskan** [comment]
because there is no "cart page", clicking cart icon check-out the cart and removes the contents of the cart that's why cart doesn't exists.

**Comment by DamianEdwards** [comment]
OK yep this is side-effect of dotnet/aspire#361. I have a fix in PR now.
